#! /bin/bash

set -e

main() {
    local -r data_dir='./data'
    local -r audio_dir="$data_dir"/audio
    local -r audio_file_path="$audio_dir/audio.wav"
    local -r yt_url='https://youtu.be/CQbkhYg2DzM'

    # Download sample audio:
    mkdir -p "$audio_dir"
    yt-dlp \
        --continue \
        --extract-audio \
        --audio-format wav \
        --audio-quality 16K \
        -o "$audio_file_path" \
        "$yt_url"

    # Convert audio to text:
    cargo run -- \
        --input-file "$audio_file_path" \
        --normalize  # Attempt to normalize the input to the supported format.
}

main "$@"
