#! /bin/bash

set -e

main() {
    local -r data_dir='./data'
    local -r models_dir="$data_dir"/models
    local -r audio_dir="$data_dir"/audio

    local -r model='base.en'
    local -r model_file="ggml-${model}.bin"
    local -r model_file_path="$models_dir/$model_file"
    local -r model_url_src="https://huggingface.co/ggerganov/whisper.cpp"
    local -r model_url_pfx="resolve/main/ggml"
    local -r model_url="$model_url_src"/"$model_url_pfx"-"$model".bin

    local -r audio_file_path_orig="$audio_dir/audio.orig.wav"
    local -r audio_file_path_norm="$audio_dir/audio.16bit16khz.wav"

    local -r yt_url='https://youtu.be/CQbkhYg2DzM'

    # Download the model:
    mkdir -p "$models_dir"
    wget \
        --continue \
        --no-config \
        --quiet \
        --show-progress \
        -O "$model_file_path" \
        "$model_url"

    # Download sample audio:
    mkdir -p "$audio_dir"
    youtube-dl \
        --continue \
        --extract-audio \
        --audio-format wav \
        --audio-quality 16K \
        -o "$audio_file_path_orig" \
        "$yt_url"

    # https://ffmpeg.org/ffmpeg.html#Stream-specifiers-1
    # "stream_type is one of following: ’v’ or ’V’ for video, ’a’ for audio,
    # ’s’ for subtitle, ’d’ for data, and ’t’ for attachments."
    local -r ffmpeg_stream_type='a'
    local -r ffmpeg_codec='pcm_s16le'
    local -r ffmpeg_audio_channels=1
    local -r ffmpeg_audio_rate=16000 # sampling frequency
    local -r ffmpeg_opt_overwrite_existing_output_file='-y'

    # Normalilze sample audio to the supported format:
    ffmpeg \
        "$ffmpeg_opt_overwrite_existing_output_file" \
        -i "$audio_file_path_orig" \
        -ar:"$ffmpeg_stream_type" "$ffmpeg_audio_rate" \
        -ac:"$ffmpeg_stream_type" "$ffmpeg_audio_channels" \
        -codec:"$ffmpeg_stream_type" "$ffmpeg_codec" \
        "$audio_file_path_norm"

    # Convert audio to text:
    cargo run -- \
        --model "$model_file_path" \
        --audio "$audio_file_path_norm"
}

main "$@"
